# Installs necessary packages for UI Research Park, Practical Data Mining course, 
# Fall 2015
# Modified from Dockerfile created by Edward Kim
#
# To build and push to Docker hub
#
# bash-3.2$ docker build -t lcdm/rppdm-standalone -f Dockerfile .
# bash-3.2$ docker login
# bash-3.2$ docker push lcdm/rppdm-standalone

FROM ipython/scipystack

MAINTAINER Robert J. Brunner <professor.brunner@gmail.com>

RUN apt-get update && \
    apt-get install -y -q \
    vim \
    wget \
    # fonts needed in seaborn 
    ttf-liberation \ 
    ttf-bitstream-vera \
    python3-bs4 \
    python3-tables 

RUN pip3 install pip --upgrade && \
    pip3 install traitlets && \
    pip3 install dask[complete]


# data_scientist is our user
# And we want to automatically start an IPython server

RUN useradd -m -u 1000 -s /bin/bash data_scientist

ADD singleuser.sh /

RUN chown 1000:1000 /singleuser.sh
RUN chmod u+x /singleuser.sh

USER data_scientist
ENV HOME /home/data_scientist
ENV SHELL /bin/bash
ENV USER data_scientist

WORKDIR /home/data_scientist/

# IPython introductions

EXPOSE 8888

# set colors for terminal prompt
RUN echo 'export PS1="\e[1;34m\u@\h:\w$ \e[0m"' >> /home/data_scientist/.bashrc


CMD ["/singleuser.sh"]
